<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-05-22T11:32:05 IST" name="Default suite" finished-at="2023-05-22T11:33:26 IST" duration-ms="81426">
    <groups>
    </groups>
    <test started-at="2023-05-22T11:32:05 IST" name="Default test" finished-at="2023-05-22T11:33:26 IST" duration-ms="81426">
      <class name="test.VerifyRegister">
        <test-method is-config="true" signature="ExtentReport()[pri:0, instance:test.VerifyRegister@14cd1699]" started-at="2023-05-22T11:32:05 IST" name="ExtentReport" finished-at="2023-05-22T11:32:06 IST" duration-ms="885" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ExtentReport -->
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:test.VerifyRegister@14cd1699]" started-at="2023-05-22T11:32:06 IST" name="launchBrowser" finished-at="2023-05-22T11:32:38 IST" duration-ms="32731" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method signature="Register()[pri:0, instance:test.VerifyRegister@14cd1699]" started-at="2023-05-22T11:32:38 IST" name="Register" finished-at="2023-05-22T11:32:43 IST" duration-ms="4860" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Register -->
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:test.VerifyRegister@14cd1699]" started-at="2023-05-22T11:32:43 IST" name="launchBrowser" finished-at="2023-05-22T11:33:14 IST" duration-ms="30582" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method signature="InvalidR1()[pri:1, instance:test.VerifyRegister@14cd1699]" started-at="2023-05-22T11:33:14 IST" name="InvalidR1" finished-at="2023-05-22T11:33:24 IST" duration-ms="10091" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Process Failed expected [Warning: You must agree to the Privacy Policy!] but found [Errort]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Process Failed expected [Warning: You must agree to the Privacy Policy!] but found [Errort]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at PageObjectModel.Common.commonassert(Common.java:11)
at test.VerifyRegister.InvalidR1(VerifyRegister.java:73)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InvalidR1 -->
        <test-method is-config="true" signature="endReport()[pri:0, instance:test.VerifyRegister@14cd1699]" started-at="2023-05-22T11:33:24 IST" name="endReport" finished-at="2023-05-22T11:33:26 IST" duration-ms="2067" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- test.VerifyRegister -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
